---
- hosts: all
  become_user: root
  become_method: sudo
  roles:
    - role: env-common-scheleaap

- hosts: desktop
  become_user: root
  become_method: sudo
  roles:
#    - role: work
    - role: env-desktop-scheleaap

- hosts: docker
  become: true
  become_user: root
  become_method: sudo
  roles:
    - role: docker
