---
- hosts: all
#  remote_user: "{{ login_username }}"
  become_user: root
  become_method: sudo
  roles:
    - role: env-common-scheleaap

- hosts: desktop
#  remote_user: "{{ login_username }}"
  become_user: root
  become_method: sudo
  roles:
#    - role: work
    - role: env-desktop-scheleaap
